# -*- coding: utf-8 -*-
"""labbuah.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wiU1Q6HkIbGbnT4psJmvRfQk98FJgYrQ
"""

import streamlit as st
import itertools
import math

st.title("🧃 Laboratorium Virtual Kombinasi Buah")

# Input buah
buah_input = st.text_input(
    "Masukkan daftar buah (pisahkan dengan koma):",
    value="Apel, Jeruk, Mangga, Pisang, Stroberi"
)

# Ubah jadi list & validasi
buah_list = [b.strip() for b in buah_input.split(",") if b.strip()]
n = len(buah_list)

# Input r
r = st.number_input("Jumlah buah yang ingin dicampur (r):", min_value=1, max_value=n, value=2, step=1)

# Validasi dan tampilkan kombinasi
if n >= r and r > 0:
    total_kombinasi = math.comb(n, r)
    hasil_kombinasi = list(itertools.combinations(buah_list, r))

    st.success(f"Jumlah kombinasi (C({n}, {r})) = {total_kombinasi}")

    st.write("### 🔽 Daftar Kombinasi:")
    for i, combo in enumerate(hasil_kombinasi, 1):
        st.write(f"{i}. {', '.join(combo)}")
else:
    st.warning("Jumlah buah (n) harus ≥ r dan r > 0.")