# -*- coding: utf-8 -*-
"""Lab_kombinasi1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDoLYxSz8vRXOJUGdSrKDeNiNyLijdbQ
"""

import streamlit as st
import itertools

st.set_page_config(layout="wide")
st.title("🍹 Laboratorium Kombinasi Buah")

st.markdown("""
Pilih 2 buah berbeda dari daftar berikut untuk membuat jus campuran.
Kombinasi tidak memperhatikan urutan.
Total kombinasi yang bisa kamu buat dari 6 buah adalah:
""")

buah_list = ["🍎 Apel", "🍌 Pisang", "🍊 Jeruk", "🥭 Mangga", "🍉 Semangka", "🍇 Anggur"]

st.success(f"Jumlah kombinasi teori = 6C2 = 15 kombinasi")

if "kombinasi_buah" not in st.session_state:
    st.session_state.kombinasi_buah = []

col1, col2 = st.columns(2)

with col1:
    pilihan = st.multiselect("Pilih 2 buah berbeda:", buah_list)

    if st.button("➕ Tambahkan Kombinasi"):
        if len(pilihan) != 2:
            st.warning("Pilih tepat 2 buah.")
        else:
            kombinasi = tuple(sorted(pilihan))
            if kombinasi not in st.session_state.kombinasi_buah:
                st.session_state.kombinasi_buah.append(kombinasi)
                st.success("Kombinasi berhasil ditambahkan.")
            else:
                st.info("Kombinasi ini sudah ada.")

    if st.button("🔁 Reset Kombinasi"):
        st.session_state.kombinasi_buah = []

with col2:
    st.subheader("🍹 Kombinasi yang Kamu Buat:")
    if st.session_state.kombinasi_buah:
        for i, k in enumerate(st.session_state.kombinasi_buah, 1):
            st.write(f"{i}. {k[0]} + {k[1]}")
        st.info(f"Total: {len(st.session_state.kombinasi_buah)} kombinasi")
        if len(st.session_state.kombinasi_buah) == 15:
            st.balloons()
            st.success("Kamu berhasil membuat semua kombinasi!")
    else:
        st.info("Belum ada kombinasi ditambahkan.")