# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oE7TGPfqaebGrsOqzIFWudX1bRkPzDpJ
"""

import streamlit as st
import math

def deg_to_rad(deg):
    return deg * math.pi / 180

def calculate_trig(angle_deg, func):
    angle_rad = deg_to_rad(angle_deg)
    try:
        if func == 'sin':
            return math.sin(angle_rad)
        elif func == 'cos':
            return math.cos(angle_rad)
        elif func == 'tan':
            val = math.tan(angle_rad)
            # Limit to a reasonable range for display if very large
            if abs(val) > 1e10:
                return float('inf') if val > 0 else float('-inf')
            return val
        elif func == 'cosec':
            sin_val = math.sin(angle_rad)
            if sin_val == 0:
                return None  # undefined
            return 1 / sin_val
        elif func == 'sec':
            cos_val = math.cos(angle_rad)
            if cos_val == 0:
                return None  # undefined
            return 1 / cos_val
        elif func == 'cotan':
            tan_val = math.tan(angle_rad)
            if tan_val == 0:
                return None  # undefined
            return 1 / tan_val
        else:
            return None
    except Exception:
        return None

st.set_page_config(
    page_title="Kalkulator Peubah Sudut",
    page_icon="📐",
    layout="centered",
    initial_sidebar_state="auto",
)

st.title("Kalkulator Peubah Sudut Trigonometri")
st.markdown("""
Gunakan aplikasi ini untuk menghitung nilai fungsi trigonometri
sin, cos, tan, cosec, sec, dan cotan berdasarkan sudut dalam derajat.
""")

# Animation - embed an educational math animation GIF (from a safe open source GIF URL)
animation_url = "https://media.giphy.com/media/l41lZxzroU33typuU/giphy.gif"
st.image(animation_url, width=320, caption="Visualisasi Animasi Trigonometri untuk Anak SMA")

# User input for angle
angle = st.slider("Pilih Sudut (dalam derajat)", min_value=0, max_value=360, value=45, step=1)

# Function selection
func = st.selectbox("Pilih Fungsi Trigonometri", ['sin', 'cos', 'tan', 'cosec', 'sec', 'cotan'])

result = calculate_trig(angle, func)

if result is None:
    st.error(f"Fungsi {func} tidak terdefinisi pada sudut {angle}°.")
else:
    st.success(f"Nilai {func}({angle}°) = {result:.6f}")

# Additional explanation for SMA students
st.markdown("""
---
### Penjelasan

- Sudut diinput dalam derajat dan dihitung dalam radian secara internal.
- Fungsi **cosec (cosecant)** = 1/sin, **sec (secant)** = 1/cos, **cotan (cotangent)** = 1/tan.
- Beberapa sudut menghasilkan fungsi yang tidak terdefinisi (seperti tan 90°).
- Gunakan slider untuk memilih sudut dan lihat hasilnya secara instan!
""")