# -*- coding: utf-8 -*-
"""Kalkulator_Aljabar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cWud_PYJmShjGzYVcpijq3RHKTey_b8
"""

from sympy import symbols, Eq, solve, sympify
from rich.console import Console
from rich.progress import track
from rich.markdown import Markdown
from rich.panel import Panel
from rich import box
from time import sleep
import random

# Setup
console = Console()
x = symbols('x')

def type_effect(text, delay=0.03):
    for char in text:
        print(char, end='', flush=True)
        sleep(delay)
    print()

def loading_animation(task_name="Menghitung..."):
    console.print(f"\n[bold yellow]{task_name}[/bold yellow]")
    for _ in track(range(20), description="⏳ Mengolah langkah..."):
        sleep(0.05)

def fancy_result(value):
    colors = ["bold cyan", "bold green", "bold magenta", "bold blue", "bold red"]
    for i in range(5):
        console.print(Panel(f"x = {value}", style=random.choice(colors), box=box.ROUNDED))
        sleep(0.3)

def solve_equation(equation_str):
    if '=' not in equation_str:
        console.print("[red]❌ Persamaan harus mengandung '='.[/red]")
        return

    left, right = equation_str.split('=')
    left_expr = sympify(left)
    right_expr = sympify(right)

    console.print("\n[bold green]📚 Langkah-langkah Menyelesaikan:[/bold green]\n")
    sleep(1)

    # Langkah 1
    step1 = f"✏️  Persamaan awal: [white]{left_expr} = {right_expr}[/white]"
    type_effect(step1)
    sleep(1)

    # Langkah 2
    zero_form = left_expr - right_expr
    step2 = f"🔄 Ubah ke bentuk nol: {left_expr} - ({right_expr}) = 0 → {zero_form} = 0"
    type_effect(step2)
    sleep(1)

    # Loading (Animasi Proses)
    loading_animation("📊 Menyelesaikan persamaan...")

    # Langkah 3
    solution = solve(Eq(left_expr, right_expr))
    step3 = f"✅ Penyelesaian ditemukan: x = {solution[0]}"
    type_effect(step3)
    sleep(1)

    # Final Result with Animasi
    console.print("\n[bold green]🎉 Hasil Akhir:[/bold green]")
    fancy_result(solution[0])

# Contoh pemakaian
if __name__ == "__main__":
    console.print("[bold cyan]🧮 KALKULATOR ALJABAR INTERAKTIF[/bold cyan]\n")
    persamaan = console.input("Masukkan persamaan (contoh: 3*x + 6 = 12): ")
    solve_equation(persamaan)