# -*- coding: utf-8 -*-
"""kalkulator_kombinasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1npeJbB67l8Q9PdwssjU8-duVlBGcipb8
"""

import streamlit as st
import pandas as pd
import requests
from streamlit_lottie import st_lottie

# Fungsi untuk memuat animasi dari URL
def load_lottie_url(url):
    try:
        r = requests.get(url)
        if r.status_code != 200:
            return None
        return r.json()
    except:
        return None

# Load animasi kaos dan celana
lottie_kaos = load_lottie_url("https://lottie.host/3f5c938b-2f70-4c02-b38e-dc5e201ff12a/WchLMtAr8Z.json")
lottie_celana = load_lottie_url("https://lottie.host/dcf44e2f-cd1a-48bb-a147-387f196a68ab/E63Ebi9UMZ.json")

# Atur tampilan halaman
st.set_page_config(page_title="Kalkulator Kombinasi Outfit", layout="wide")

st.title("👕👖 Kalkulator Kombinasi Outfit Interaktif")

st.markdown("### Soal:")
st.info("Seorang siswa memiliki **4 kaos** dan **3 celana**. Berapa banyak cara memilih 2 pakaian berbeda (kaos dan celana) untuk kombinasi outfit?")

st.markdown("---")
st.markdown("## 🔢 Masukkan Jumlah Kaos dan Celana")

# Input jumlah kaos dan celana
col1, col2 = st.columns(2)

with col1:
    jumlah_kaos = st.number_input("Jumlah Kaos", min_value=0, value=4, step=1)
    if lottie_kaos:
        st_lottie(lottie_kaos, height=180, key="kaos")

with col2:
    jumlah_celana = st.number_input("Jumlah Celana", min_value=0, value=3, step=1)
    if lottie_celana:
        st_lottie(lottie_celana, height=180, key="celana")

# Kalkulasi dan tampilan hasil
if jumlah_kaos > 0 and jumlah_celana > 0:
    total_kombinasi = jumlah_kaos * jumlah_celana
    st.success(f"👕 x 👖 Total kombinasi outfit: **{total_kombinasi}** (1 kaos × 1 celana)")

    st.markdown("### 📋 Tabel Kombinasi Outfit")
    kombinasi = pd.DataFrame([
        {"Kaos": f"Kaos {i+1}", "Celana": f"Celana {j+1}"}
        for i in range(jumlah_kaos)
        for j in range(jumlah_celana)
    ])
    st.dataframe(kombinasi, use_container_width=True)
else:
    st.warning("Masukkan jumlah kaos dan celana lebih dari 0.")

st.markdown("---")
st.caption("Dibuat dengan ❤️ menggunakan Streamlit")