# -*- coding: utf-8 -*-
"""Kombinasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDoLYxSz8vRXOJUGdSrKDeNiNyLijdbQ
"""

import streamlit as st
import math

# Judul aplikasi
st.title("Kalkulator Kombinasi Interaktif")

st.write("""
Kalkulator ini menghitung nilai kombinasi (C(n, r)) berdasarkan rumus:

**C(n, r) = n! / (r! × (n - r)!)**
""")

# Input dari pengguna
n = st.number_input("Masukkan nilai n (bilangan bulat ≥ 0)", min_value=0, step=1, value=5)
r = st.number_input("Masukkan nilai r (bilangan bulat ≥ 0 dan ≤ n)", min_value=0, step=1, value=3)

# Validasi input
if r > n:
    st.error("Nilai r tidak boleh lebih besar dari n.")
else:
    # Fungsi untuk menghitung kombinasi
    def kombinasi(n, r):
        return math.comb(n, r)

    hasil = kombinasi(n, r)
    st.success(f"Hasil kombinasi C({n}, {r}) adalah **{hasil}**")