# -*- coding: utf-8 -*-
"""Kalkulator_Peubah_Sudut_Trigonometri.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B-Tds8g7xrwfTtoBVnNgCyWN1DnE-1pp
"""

import streamlit as st
import math

def deg_to_rad(deg):
    return deg * math.pi / 180

def calculate_trig(angle_deg, func):
    angle_rad = deg_to_rad(angle_deg)
    try:
        if func == 'sin':
            return math.sin(angle_rad)
        elif func == 'cos':
            return math.cos(angle_rad)
        elif func == 'tan':
            val = math.tan(angle_rad)
            if abs(val) > 1e10:
                return float('inf') if val > 0 else float('-inf')
            return val
        elif func == 'cosec':
            sin_val = math.sin(angle_rad)
            if sin_val == 0:
                return None
            return 1 / sin_val
        elif func == 'sec':
            cos_val = math.cos(angle_rad)
            if cos_val == 0:
                return None
            return 1 / cos_val
        elif func == 'cotan':
            tan_val = math.tan(angle_rad)
            if tan_val == 0:
                return None
            return 1 / tan_val
        else:
            return None
    except Exception:
        return None

st.set_page_config(
    page_title="Kalkulator Peubah Sudut dengan Animasi",
    page_icon="📐",
    layout="centered",
    initial_sidebar_state="auto",
)

st.title("Kalkulator Peubah Sudut Trigonometri dengan Animasi Sudut")
st.markdown("""
Gunakan aplikasi ini untuk menghitung nilai fungsi trigonometri
dan melihat animasi visualisasi bentuk sudut.
""")

angle = st.slider("Pilih Sudut (dalam derajat)", 0, 360, 45)

func = st.selectbox("Pilih Fungsi Trigonometri", ['sin', 'cos', 'tan', 'cosec', 'sec', 'cotan'])

result = calculate_trig(angle, func)
if result is None:
    st.error(f"Fungsi {func} tidak terdefinisi pada sudut {angle}°.")
else:
    st.success(f"Nilai {func}({angle}°) = {result:.6f}")

st.markdown("---")

st.subheader("Animasi Visualisasi Sudut")

# Animated SVG or HTML + CSS angle visualizer
# The animation: a circle with an angle arc and a rotating arm that points at the current angle.
# We'll implement a small HTML + CSS snippet with animation to illustrate the angle arm rotating continuously,
# but the angle input will control the fixed angle shown in the visualization.

# Because we want the angle from user input, the arm will be fixed at that angle.
# We'll also animate the arc stroke-dashoffset for smooth arc drawing.

html_animation = f"""
<style>
  .container {{
    width: 240px;
    height: 240px;
    margin: 0 auto;
    user-select: none;
  }}
  svg {{
    width: 100%;
    height: 100%;
  }}
  .circle-bg {{
    fill: #e0e0e0;
  }}
  .arc {{
    fill: none;
    stroke: #4f46e5;
    stroke-width: 10;
    stroke-linecap: round;
    stroke-dasharray: 377; /* 2 * pi * r (r=60) */
    stroke-dashoffset: 377;
    animation: drawArc 1s forwards;
  }}
  @keyframes drawArc {{
    from {{
      stroke-dashoffset: 377;
    }}
    to {{
      stroke-dashoffset: {377 - (377 * angle/360)};
    }}
  }}
  .arm {{
    stroke: #ef4444;
    stroke-width: 6;
    stroke-linecap: round;
    transform-origin: 120px 120px;
    transform-box: fill-box;
    transform: rotate({angle}deg);
    transition: transform 0.6s ease;
  }}
  .center-circle {{
    fill: #4f46e5;
  }}
</style>

<div class="container" aria-label="Visualisasi sudut {angle} derajat">
  <svg viewBox="0 0 240 240" role="img" aria-labelledby="title desc">
    <title>Visualisasi Sudut</title>
    <desc>Gambar menunjukkan sudut dengan besar {angle} derajat.</desc>
    <circle class="circle-bg" cx="120" cy="120" r="60" />
    <path class="arc" d="M180 120 A60 60 0 {1 if angle > 180 else 0} 1 {120 + 60 * math.cos(math.radians(angle)):.3f} {120 - 60 * math.sin(math.radians(angle)):.3f}" />
    <line class="arm" x1="120" y1="120" x2="180" y2="120" />
    <circle class="center-circle" cx="120" cy="120" r="8" />
  </svg>
</div>
"""

st.components.v1.html(html_animation, height=260, scrolling=False)

st.markdown("""
---
### Penjelasan Animasi
- Lingkaran besar berwarna abu-abu muda sebagai dasar.
- Busur berwarna ungu menunjukkan besar sudut yang dipilih.
- Garis merah sebagai arm menunjuk ke arah sudut tersebut.
- Titik ungu di tengah lingkaran sebagai pusat rotasi.
""")