# -*- coding: utf-8 -*-
"""Kalkulator_Kerucut.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKu63z-F1hJd4rbHv1LS_FM5bSCYCFzs
"""

import streamlit as st
import math

st.title("📐 Kalkulator Luas Permukaan dan Volume Kerucut")

# Input pengguna
r = st.number_input("Masukkan jari-jari alas (r) dalam cm:", min_value=0.0, format="%.2f")
s = st.number_input("Masukkan panjang garis pelukis (s) dalam cm:", min_value=0.0, format="%.2f")
t = st.number_input("Masukkan tinggi kerucut (t) dalam cm:", min_value=0.0, format="%.2f")

# Tombol hitung
if st.button("Hitung"):
    if r > 0 and s > 0 and t > 0:
        luas_permukaan = math.pi * r * (r + s)
        volume = (1/3) * math.pi * r**2 * t

        st.success(f"Luas Permukaan Kerucut: {luas_permukaan:.2f} cm²")
        st.success(f"Volume Kerucut: {volume:.2f} cm³")
    else:
        st.warning("Mohon masukkan semua nilai (r, s, t) lebih dari 0")