# -*- coding: utf-8 -*-
"""Kalkulator_Konverter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cWud_PYJmShjGzYVcpijq3RHKTey_b8
"""

import streamlit as st
import time

# Konversi satuan biasa
def convert_with_ratio(value, from_unit, to_unit, unit_dict):
    return value * unit_dict[from_unit] / unit_dict[to_unit]

# Konversi suhu khusus
def convert_temperature(value, from_unit, to_unit):
    if from_unit == to_unit:
        return value
    if from_unit == "C":
        return value * 9/5 + 32 if to_unit == "F" else value + 273.15
    if from_unit == "F":
        return (value - 32) * 5/9 if to_unit == "C" else (value - 32) * 5/9 + 273.15
    if from_unit == "K":
        return value - 273.15 if to_unit == "C" else (value - 273.15) * 9/5 + 32

# Data konversi
unit_types = {
    "Jarak": {
        "units": {"km": 1000, "m": 1, "cm": 0.01, "mm": 0.001},
        "converter": convert_with_ratio
    },
    "Luas": {
        "units": {"km2": 1_000_000, "m2": 1, "cm2": 0.0001, "mm2": 0.000001},
        "converter": convert_with_ratio
    },
    "Berat": {
        "units": {"ton": 1_000_000, "kg": 1000, "ons": 100, "g": 1, "mg": 0.001},
        "converter": convert_with_ratio
    },
    "Waktu": {
        "units": {"hari": 86400, "jam": 3600, "menit": 60, "detik": 1},
        "converter": convert_with_ratio
    },
    "Volume": {
        "units": {"m3": 1000, "liter": 1, "ml": 0.001, "cm3": 0.001},
        "converter": convert_with_ratio
    },
    "Suhu": {
        "units": {"C": 1, "F": 1, "K": 1},
        "converter": convert_temperature
    }
}

# Streamlit UI
st.set_page_config(page_title="Konverter Satuan Interaktif", page_icon="🧮")
st.title("🧮 Kalkulator Konversi Interaktif")
st.markdown("Konversi satuan lengkap dengan animasi yang menarik.")

# Pilih konversi
conversion_type = st.selectbox("🔧 Jenis Konversi", list(unit_types.keys()))
unit_data = unit_types[conversion_type]
units = list(unit_data["units"].keys())

# Input pengguna
value = st.number_input("Masukkan nilai", min_value=0.0, value=1.0)
from_unit = st.selectbox("Dari satuan", units)
to_unit = st.selectbox("Ke satuan", units)

# Tombol konversi
if st.button("🚀 Konversi"):
    progress = st.progress(0, text="⏳ Menghitung...")
    for i in range(100):
        time.sleep(0.01)
        progress.progress(i + 1, text=f"⏳ Menghitung... {i + 1}%")

    with st.spinner("📊 Menyusun hasil..."):
        time.sleep(0.5)
        if conversion_type == "Suhu":
            result = unit_data["converter"](value, from_unit, to_unit)
        else:
            result = unit_data["converter"](value, from_unit, to_unit, unit_data["units"])

    st.balloons()  # 🎈 Efek animasi visual
    st.success("✅ Konversi selesai!")
    st.markdown(f"""
        <div style='background-color:#d1ecf1;padding:20px;border-radius:10px'>
            <h3 style='color:#0c5460;'>Hasil:</h3>
            <p style='font-size:24px;color:#004085;'><b>{value} {from_unit} = {result:.4f} {to_unit}</b></p>
        </div>
    """, unsafe_allow_html=True)