# -*- coding: utf-8 -*-
"""Lab_kombinasi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tDoLYxSz8vRXOJUGdSrKDeNiNyLijdbQ
"""

import streamlit as st
import pandas as pd
import requests
from streamlit_lottie import st_lottie

# Fungsi untuk memuat animasi dari Lottie
def load_lottie_url(url):
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()

# Animasi kaos & celana (bisa ganti dari lottiefiles.com)
kaos_anim = load_lottie_url("https://lottie.host/3f5c938b-2f70-4c02-b38e-dc5e201ff12a/WchLMtAr8Z.json")
celana_anim = load_lottie_url("https://lottie.host/dcf44e2f-cd1a-48bb-a147-387f196a68ab/E63Ebi9UMZ.json")

st.set_page_config(page_title="Laboratorium Virtual Kombinasi", layout="wide")
st.title("👨‍🔬 Laboratorium Virtual Kombinasi Pakaian")

st.markdown("### Soal:")
st.info("Seorang siswa memiliki **4 kaos** dan **3 celana**. Berapa banyak cara memilih 2 pakaian berbeda (kaos dan celana)?")

# Bagian input interaktif
col1, col2 = st.columns(2)
with col1:
    jml_kaos = st.slider("Jumlah Kaos", 1, 10, 4)
    if kaos_anim:
        st_lottie(kaos_anim, height=180)
with col2:
    jml_celana = st.slider("Jumlah Celana", 1, 10, 3)
    if celana_anim:
        st_lottie(celana_anim, height=180)

# Tampilkan kombinasi
st.markdown("### 🔄 Kombinasi Otomatis")
kombinasi = pd.DataFrame([
    {"Kaos": f"Kaos {i+1}", "Celana": f"Celana {j+1}"}
    for i in range(jml_kaos)
    for j in range(jml_celana)
])
st.write(f"Total kombinasi = **{len(kombinasi)}**")
st.dataframe(kombinasi, use_container_width=True)

# Fitur interaktif pengelompokan
st.markdown("### ✏️ Eksperimen Sendiri: Buat Kombinasi Manual")

daftar_kaos = [f"Kaos {i+1}" for i in range(jml_kaos)]
daftar_celana = [f"Celana {j+1}" for j in range(jml_celana)]

pilihan_kaos = st.selectbox("Pilih Kaos", daftar_kaos)
pilihan_celana = st.selectbox("Pilih Celana", daftar_celana)

if st.button("Tambahkan Kombinasi"):
    if "kombinasi_manual" not in st.session_state:
        st.session_state.kombinasi_manual = []
    st.session_state.kombinasi_manual.append((pilihan_kaos, pilihan_celana))

if "kombinasi_manual" in st.session_state:
    st.markdown("#### 📝 Kombinasi yang Kamu Buat:")
    df_manual = pd.DataFrame(st.session_state.kombinasi_manual, columns=["Kaos", "Celana"])
    st.dataframe(df_manual)

st.markdown("---")
st.caption("🧪 Dibuat oleh ChatGPT untuk pembelajaran kombinasi secara visual dan eksploratif.")