# -*- coding: utf-8 -*-
"""Kalkulator_Turunan dan Integral.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cWud_PYJmShjGzYVcpijq3RHKTey_b8
"""

import sys
import time
from sympy import symbols, diff, integrate, sympify, pretty

def animate_text(text, delay=0.04):
    for char in text:
        print(char, end='', flush=True)
        time.sleep(delay)
    print()

def kalkulator_turunan():
    x = symbols('x')
    fungsi_str = input("Masukkan fungsi f(x) yang ingin diturunkan (contoh: x**3 + 2*x + 1): ")
    try:
        fungsi = sympify(fungsi_str)
        turunan = diff(fungsi, x)
        animate_text("\nMenghitung turunan...")
        animate_text("Turunan dari fungsi f(x) adalah:\n")
        animate_text(pretty(turunan), delay=0.02)
        animate_text(f"\nTurunan dalam bentuk fungsi: {turunan}")
    except Exception as e:
        print(f"Terjadi kesalahan: {e}")

def kalkulator_integral():
    x = symbols('x')
    fungsi_str = input("Masukkan fungsi f(x) yang ingin diintegralkan (contoh: x**2 + 3*x + 1): ")
    try:
        fungsi = sympify(fungsi_str)
        integral = integrate(fungsi, x)
        animate_text("\nMenghitung integral...")
        animate_text("Integral tak tentu dari fungsi f(x) adalah:\n")
        animate_text(pretty(integral + symbols('C')), delay=0.02)
        animate_text(f"\nIntegral dalam bentuk fungsi: {integral} + C")
    except Exception as e:
        print(f"Terjadi kesalahan: {e}")

def main():
    animate_text("Kalkulator Turunan dan Integral!", delay=0.03)
    while True:
        print("\nPilih operasi:")
        print("1. Hitung Turunan")
        print("2. Hitung Integral")
        print("0. Keluar")
        pilihan = input("Pilihan Anda: ")
        if pilihan == '1':
            kalkulator_turunan()
        elif pilihan == '2':
            kalkulator_integral()
        elif pilihan == '0':
            animate_text("Terima kasih sudah menggunakan program ini! Sampai jumpa!", delay=0.03)
            break
        else:
            print("Pilihan tidak valid, silakan coba lagi.")

if __name__ == "__main__":
    main()